<?php

namespace Labs\BackBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PartnerRepository extends EntityRepository
{


    public function findOne($entity)
    {
        $qb = $this->createQueryBuilder('p');
        $qb->where($qb->expr()->eq('p.id', ':id'));
        $qb->setParameter(':id', $entity);
        return $qb->getQuery()->getOneOrNullResult();
    }


    public function findLimit($max)
    {
        $qb = $this->createQueryBuilder('p');
        $qb->setMaxResults($max);
        return $qb->getQuery()->getResult();
    }
}
