<?php

namespace Labs\BackBundle\Repository;

/**
 * ServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $entity
     * @return mixed
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function findOne($entity)
    {
        $qb = $this->createQueryBuilder('s');
        $qb->where($qb->expr()->eq('s.id', ':id'));
        $qb->setParameter(':id', $entity);
        return $qb->getQuery()->getOneOrNullResult();
    }

    /**
     * @return mixed
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function findPage()
    {
        $qb = $this->createQueryBuilder('s');
        return $qb->getQuery()->getOneOrNullResult();
    }

    /**
     * @param $max
     * @return array
     */
    public function findLimit($max)
    {
        $qb = $this->createQueryBuilder('s');
        $qb->setMaxResults($max);
        return $qb->getQuery()->getResult();
    }
    
}
